### ISSUE TITLE
Reload / recompile of css not working

### ISSUE THREAD

**Issue by Lelith** [mcmakler/components#14]
Hey *,

**issue description:** storybook server is running via `npm run serve` and a demo of the react component is showing in storybook demo.
i am changing now the styles under `components-style/src/components` 

when i save the changes its not updating / recompiling the current changes. 

**workaround** atm with nodemon:
`nodemon --watch src --exec "npm run build" -e scss
`

**Comment by baruchvlz** [comment]
Open PR ( #15 ) suggests using gulp to watch changes and remove the files to the lib folder. Open for suggestions / changes.
