### ISSUE TITLE
Consider adding lerna script

### ISSUE THREAD

**Issue by TejasQ** [mcmakler/components#3]
Why make your consumers install Lerna globally? Consider an alternative:
- Have lerna as a project's devDependency
- Add `bootstrap` under `scripts` to `package.json` that calls `lerna bootstrap` internally

Then, `yarn bootstrap` will run Lerna from `./node_modules/.bin` and it removes the need for the user to potentially unnecessarily install Lerna globally.

**Comment by TejasQ** [comment]
You could also:

```json
{
  "scripts": {
    "lerna": "lerna"
  }
}
```

which would let you do `yarn lerna [command]` without having to do all the mapping.

**Comment by baruchvlz** [comment]
That's not a bad idea, but I don't think there're many other scripts outside of `bootstrap` that would be used by anyone other than us. Not everyone will be able to publish ;)

**Comment by TejasQ** [comment]
Although if you want to run `test` in ALL packages, `lerna run test` would be convenient. :D

**Comment by baruchvlz** [comment]
Tests are not implemented yet, but should be something to consider.
